"""The regression instrument: graph hashes byte-match the reference oracle.

`tests/graph_hash_bank.json` was GENERATED BY THE OLD TREE (torchcg at
`a58f24a0`, the tcg#88 merge) on the tiny-UNet fixture and checked in unchanged.
It is the only thing standing between a rewrite and a silently re-keyed fleet:
every artifact in the store is addressed by these strings, so a rewrite that
moves one has orphaned the corpus whether or not anything else is broken.

Regenerate ONLY with a stated reason. The bank moving is a fleet-wide re-mint.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fixture import UNET_PARAMS, export_unet, tiny_unet

torch = pytest.importorskip("torch")
pytest.importorskip("diffusers")

BANK = json.loads((Path(__file__).parent / "graph_hash_bank.json").read_text())


def _dynamic_export():
    from torchcg.identity import build_call_ingress

    unet = tiny_unet()
    batch = torch.export.Dim("batch", min=2, max=8)
    args = (torch.zeros(2, 4, 8, 8), torch.zeros(()), torch.zeros(2, 77, 16))
    kwargs = {"return_dict": False}
    program = torch.export.export(
        unet, args, kwargs, strict=False,
        dynamic_shapes=({0: batch}, None, {0: batch}, None),
    )
    return program, build_call_ingress(program, UNET_PARAMS, args, kwargs)


@pytest.mark.parametrize("batch", (1, 2))
def test_static_graph_hash_matches_the_bank(batch: int) -> None:
    from torchcg.identity import graph_hash

    program, ingress = export_unet(batch)
    assert graph_hash(program, ingress) == BANK[f"static_batch{batch}"]
    assert ingress.digest() == BANK[f"static_batch{batch}_ingress"]


def test_dynamic_graph_hash_matches_the_bank() -> None:
    from torchcg.identity import graph_hash

    program, ingress = _dynamic_export()
    assert graph_hash(program, ingress) == BANK["dynamic_batch_2_8"]
    assert ingress.digest() == BANK["dynamic_batch_2_8_ingress"]


def test_passes_are_a_derivation_input() -> None:
    """A pass that does not change the trace still cannot share an identity."""

    from torchcg.identity import graph_hash

    program, ingress = _dynamic_export()
    assert graph_hash(program, ingress, passes=("fuse-qkv",)) == (
        BANK["dynamic_batch_2_8_passes"]
    )
    assert graph_hash(program, ingress) != graph_hash(program, ingress, passes=("fuse-qkv",))


def test_a_different_shape_is_a_different_graph() -> None:
    """The RED ARM for the whole bank: if these ever collide, the bank proves
    nothing, because it would match no matter what the renderer did."""

    assert BANK["static_batch1"] != BANK["static_batch2"]


def test_the_canonical_form_reads_the_exported_symbol_not_the_live_one() -> None:
    """tcg#78, the single most load-bearing subtlety, asked directly.

    `SymNode._expr` is the symbol the EXPORT established; `.expr` is a property
    that folds in whatever the ShapeEnv has been told since. An AOTI compile
    shares the program's ShapeEnv and installs replacements there (measured:
    `.expr` s53 -> 2 across one compile, `._expr` still s53), so a renderer
    reading `.expr` describes COMPILER STATE -- the same program hashes
    differently before and after a compile.

    The two spellings only disagree once something has narrowed the symbol, so
    the guard hands the renderer a node where they disagree BY CONSTRUCTION.
    It goes red the moment `_render_symbol` prefers `.expr`.
    """

    import sympy

    from torchcg.identity import _render_symbol, _Symbols

    exported, live = sympy.Symbol("s53"), sympy.Integer(2)

    class _Node:
        _expr = exported
        expr = live

    class _Sym:
        node = _Node()

    symbols = _Symbols()
    rendered = _render_symbol(_Sym(), symbols)
    assert rendered == "S0", (
        f"the renderer produced {rendered!r}: it read `.expr` ({live}, compiler "
        f"state) instead of `._expr` ({exported}, what the export established)"
    )
    assert symbols.known() == (("s53", "S0"),)
