"""Mint and reuse verified PyTorch AOTInductor graphs through tensorfs."""

from .adopt import (
    AdoptError,
    AdoptSession,
    ArtifactLoader,
    Hole,
    UnclaimedMark,
)
from .artifact import (
    ARTIFACT_METADATA_FIELDS,
    COMPILED_GRAPH_FORMAT,
    ArtifactError,
    ArtifactFormatSkew,
)
from .compiler import CompileError, DroppedOptimization, declared_input_layout
from .declaration import (
    GRAPH_INTERFACE_FORMAT,
    DeclarationError,
    GraphSpecialization,
    GraphSpecializationDeclaration,
    RetiredGraphInterface,
    RuntimeCompatibility,
)
from .discovery import DiscoveryError, discover_lane, discover_modules
from .document import (
    DOCUMENT_FORMAT,
    DocumentError,
    GraphRecord,
    GraphSetDocument,
    LaneGraphs,
)
from .dynamic import DimPolicy
from .engine import (
    AdmissionError,
    Engine,
    EnsureOutcome,
    EnsureResult,
)

# `torchcg.hollow` (the weights-free derive session, tcg#45) is DELIBERATELY
# not re-exported here: it is the PUBLISH-time surface and it names model
# libraries (diffusers/transformers loader interception), so importing it from
# the package root would put those libraries on every consumer's serve-role
# import closure (pgw#1331's fence measured exactly that). The derive imports
# `torchcg.hollow` by its own name.
from .graph_identity import (
    ENV_SCHEME,
    GRAPH_SCHEME,
    STACK_NAMES,
    STACK_PREFIXES,
    EnvIdentity,
    GraphIdentityError,
    compile_stack,
    graph_hash,
    is_compile_relevant,
    is_graph_hash,
    require_stack,
)
from .identity import (
    ARTIFACT_KIND,
    GRAPH_SPECIALIZATION_BLOCK,
    REQUIRED_AXES,
    CompiledGraphKey,
    IdentityError,
    is_compiled_graph_key,
)
from .ingress import (
    CallIngress,
    CallInput,
    IngressError,
    build_call_ingress,
    exported_input_name,
)
from .lane import (
    LANE_JOIN,
    LaneError,
    LaneRef,
    parse_lane_id,
    require_lane_id,
    require_pass_ref,
    require_passes,
    require_targets,
    resolve_target,
)
from .layout import (
    CATALOG as LAYOUT_CATALOG,
)
from .layout import (
    CONTIGUOUS,
    LayoutError,
    LayoutMorphism,
    require_morphism,
)
from .quantize import (
    KeptModule,
    ModuleSelect,
    QuantPlan,
    QuantRecipe,
    RecipeError,
    RecipeQuantize,
    applied_lane_row,
    is_resident,
    plan_quant,
)
from .requirements import (
    ArtifactCandidate,
    EnvironmentMismatch,
    RequirementsError,
    RequirementsManifest,
    assert_exact_env,
    rank,
)
from .runner import CompiledGraphRunner, ConstantBindingError, VerifiedGraph
from .selection import (
    FeedNormalization,
    GraphSpecializationCandidate,
    IngressMiss,
    MissReason,
    NormalizationKind,
    PresentedCall,
    PresentedValue,
    RealignReason,
    Selection,
    SelectionError,
    SelectionOutcome,
    SpecializationReport,
    describe_call,
    select,
)
from .serve import (
    CompiledGraphCall,
    MaterializedGraph,
    aoti_loader,
    materialize,
    module_device,
    resident_constants,
)
from .storage import (
    QuarantinedArtifact,
    StorageError,
    StoredCompiledGraph,
    StoreOutcome,
    StoreResult,
)
from .store import GraphStore, LocalGraphStore, PublishOutcome, StoreError, holes
from .transform import (
    SIDE_TABLE_FORMAT,
    CallInputs,
    OffDomain,
    PrecomputeAndFree,
    Precomputed,
    Produced,
    SideTableStore,
    TransformError,
    TransformMode,
    TransformOrderError,
    TransformPass,
    TransformPlan,
    TransformReport,
    TransformSession,
    TransformSet,
    canonical_key,
    handle,
    installed_passes,
    module_bytes,
    register_pass,
    registered_passes,
    resolve_pass,
    tensor_bytes,
)

__all__ = [
    "SIDE_TABLE_FORMAT",
    "CallInputs",
    "KeptModule",
    "ModuleSelect",
    "OffDomain",
    "PrecomputeAndFree",
    "Precomputed",
    "Produced",
    "QuantPlan",
    "QuantRecipe",
    "RecipeError",
    "RecipeQuantize",
    "SideTableStore",
    "TransformError",
    "TransformMode",
    "TransformOrderError",
    "TransformPass",
    "TransformPlan",
    "TransformReport",
    "TransformSession",
    "TransformSet",
    "applied_lane_row",
    "canonical_key",
    "handle",
    "installed_passes",
    "is_resident",
    "module_bytes",
    "plan_quant",
    "register_pass",
    "registered_passes",
    "require_pass_ref",
    "require_passes",
    "resolve_pass",
    "tensor_bytes",
    "ARTIFACT_KIND",
    "ARTIFACT_METADATA_FIELDS",
    "AdmissionError",
    "AdoptError",
    "AdoptSession",
    "ArtifactCandidate",
    "ArtifactError",
    "ArtifactFormatSkew",
    "ArtifactLoader",
    "CompileError",
    "CONTIGUOUS",
    "COMPILED_GRAPH_FORMAT",
    "DroppedOptimization",
    "LAYOUT_CATALOG",
    "LayoutError",
    "LayoutMorphism",
    "declared_input_layout",
    "require_morphism",
    "DOCUMENT_FORMAT",
    "DimPolicy",
    "DiscoveryError",
    "DocumentError",
    "ENV_SCHEME",
    "EnvIdentity",
    "EnvironmentMismatch",
    "LaneRef",
    "GRAPH_SCHEME",
    "GraphIdentityError",
    "GraphRecord",
    "GraphSetDocument",
    "GraphStore",
    "Hole",
    "UnclaimedMark",
    "LaneError",
    "LaneGraphs",
    "LocalGraphStore",
    "PublishOutcome",
    "RequirementsError",
    "RequirementsManifest",
    "StoreError",
    "assert_exact_env",
    "compile_stack",
    "discover_lane",
    "discover_modules",
    "graph_hash",
    "holes",
    "is_compile_relevant",
    "require_stack",
    "STACK_NAMES",
    "STACK_PREFIXES",
    "is_graph_hash",
    "rank",
    "LANE_JOIN",
    "parse_lane_id",
    "require_lane_id",
    "require_targets",
    "resolve_target",
    "CompiledGraphKey",
    "CompiledGraphCall",
    "CompiledGraphRunner",
    "CallIngress",
    "CallInput",
    "SpecializationReport",
    "ConstantBindingError",
    "MaterializedGraph",
    "VerifiedGraph",
    "aoti_loader",
    "materialize",
    "module_device",
    "resident_constants",
    "GRAPH_INTERFACE_FORMAT",
    "DeclarationError",
    "RetiredGraphInterface",
    "Engine",
    "EnsureOutcome",
    "EnsureResult",
    "FeedNormalization",
    "GRAPH_SPECIALIZATION_BLOCK",
    "GraphSpecializationCandidate",
    "GraphSpecializationDeclaration",
    "GraphSpecialization",
    "IdentityError",
    "REQUIRED_AXES",
    "IngressError",
    "IngressMiss",
    "MissReason",
    "NormalizationKind",
    "PresentedCall",
    "PresentedValue",
    "QuarantinedArtifact",
    "RealignReason",
    "RuntimeCompatibility",
    "Selection",
    "SelectionError",
    "SelectionOutcome",
    "StorageError",
    "StoreOutcome",
    "StoreResult",
    "StoredCompiledGraph",
    "build_call_ingress",
    "describe_call",
    "exported_input_name",
    "is_compiled_graph_key",
    "select",
]
